Load in NumPy

In [77]:
import numpy as np
import math
import sys

Numpy is for numbers only unlike list which is any valid object
Numpy usese contiguous memory (all data is next to each others instead of scatted like in lists)
    This transate computer wise to better cache usage

Applicatiosn of Numpy
MATLAB replacement
plotting(Matplotlib)
backend (pandas)
Machine Learning

In [17]:
a = np.array([1,2,3], dtype ='int16') # we are directly specifying the size in the event we want to save space
a

array([1, 2, 3], dtype=int16)

In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]]) #if placing an array within an array use []
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [19]:
#Get Dimension
print(a.ndim) #line 
print(b.ndim)# square
#3d is a cube

1
2


In [20]:
#get shape
print(a.shape)
b.shape #2 rows 3 columsn

(3,)


(2, 3)

In [21]:
#Get type
print(a.dtype)
b.dtype

int16


dtype('float64')

In [23]:
#get type
print(a.itemsize)
b.itemsize

2


8

In [25]:
#get total type
a.nbytes

6

## Accessing/Changing specific elements, rows, columns, etc

In [27]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
#get a specific element [r,c]
a[1,-2] # you can negatively index the array like py lists

13

In [30]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [32]:
#get a specific column
a[:,2]

array([ 3, 10])

In [36]:
# Getting a little more fancy [startingindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [38]:
#replace a specific value
a[1,5] = 20
print(a)

a[:,2] = [1,2]# replacing all rows with column #3
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


3-d example

In [41]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [42]:
#get specific element (work outside in)
b[0,1,1] #we want to access 4 in this example

4

In [45]:
# replace
b[:,1,:] #we want to see the second row
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Intializing Different Types of Arrays

In [49]:
# all 0s matrix (build-in function)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
# all in 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [52]:
#any other number
np.full((2,2),99) # first value is shape/ second is the assigned value to all cells

array([[99, 99],
       [99, 99]])

In [55]:
#Any other number (full like)
np.full(a.shape,4) #np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
#random decimal numbers
np.random.rand(4,2)

array([[0.90044246, 0.84370887],
       [0.05448919, 0.47477329],
       [0.7585929 , 0.06341023],
       [0.72969514, 0.54038768]])

In [61]:
#random Integer Values
np.random.randint(0,7, size=(3,3)) # (start, stop, size='default') default = 1

array([[3, 6, 2],
       [3, 4, 2],
       [2, 4, 2]])

In [62]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [87]:
q1_arr = np.ones((5,5))
q1_arr[1:-1,1:-1] = 0 # the surrounding values of the array set to 1

# somewhat works for odd sized array but not so much for even values (as there is no specific center)
x_center, y_center = q1_arr.shape
x_center = int(x_center/2)
y_center = int(y_center/2)

q1_arr[x_center,y_center] = 9
print(q1_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [89]:
#free code camp answer
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z # better is 1:-1
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!

In [93]:
a = np.array([1,2,3])
b = a.copy() # so that we do not change array a
b[0] = 100 # because we are pointing to array a it will change the value aswell
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [100]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [101]:
a + 2

array([3, 4, 5, 6])

In [102]:
a - 2

array([-1,  0,  1,  2])

In [103]:
a * 2

array([2, 4, 6, 8])

In [104]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [105]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [106]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [107]:
#take the sin of all values. I<m sure it works for all trigonometry
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Comprehensive list can be found there:
https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.math.html

## Linear Algebra

In [112]:
# multiplying matrices
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [113]:
# find the determinate
c = np.identity(3) #row of one down the middle
print(c)
np.linalg.det(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

More info at https://docs.scipy.org/doc/numpy-1.12.0/reference/routines.linalg.html

## Statistics

In [115]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [116]:
np.min(stats, axis=0)

array([1, 2, 3])

In [117]:
np.max(stats) #there is the axis option that allows you to do rows and columns

6

In [120]:
np.sum(stats)#there is the axis option that allows you to do rows and columns

21

## Reorganizing Arrays

In [124]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1)) # note has to have the same amount of values (musmatch)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [126]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
#horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from File

In [147]:
# in this example its a txt.file 
filedata = np.genfromtxt('data.txt', delimiter=",") #be careful with the delimiter
filedata = filedata.astype('int32')#default is flaot
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Avanced Indexing

In [146]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [149]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [151]:
# you can index with a list in NumPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [155]:
np.any(filedata > 50, axis=0) #tells us which columns have a value about 50. 
#interresting way to go though a large array when searching for multiple occurances of True conditions

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [159]:
 (~((filedata > 50) & (filedata < 100))) #~ indicates not

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

Question 2

In [194]:
# Super powerful way to create specific matrices: create a 1d array and the reshape it into the desired matrix
q2_m = np.arange(1,31).reshape(6,5)
print(q2_m)
print('a')
print(q2_m[2:4,0:2]) #[rows,columns] (y,x) in a cartesian mind
print('b')
print(q2_m[[0,1,2,3],[1,2,3,4]])
print('c')
print(q2_m[[0,4,5],3:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
a
[[11 12]
 [16 17]]
b
[ 2  8 14 20]
c
[[ 4  5]
 [24 25]
 [29 30]]
